# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: news
    weight: 10

  - name: Calls
    identifier: calls
    weight: 20
  - name: Call for Papers
    parent: calls
    url: cfp
    weight: 21
  - name: Call for Posters
    parent: calls
    url: cfposters
    weight: 22
  - name: Call for Sponsors
    parent: calls
    url: cfs
    weight: 23
  - name: Call for Volunteers
    parent: calls
    url: cfv
    weight: 24

  - name: Program
    identifier: program
    weight: 30
  - name: Workshop
    parent: program
    url: program
    weight: 31
  - name: Poster
    parent: program
    url: posters
    weight: 32
  - name: Accepted Papers
    parent: program
    url: papers
    weight: 33

  - name: Attend
    identifier: attend
    weight: 40
  - name: Registration
    parent: attend
    url: registration
    weight: 41
  - name: Visa
    parent: attend
    url: visa
    weight: 42
  - name: Hotel
    parent: attend
    url: hotel
    weight: 43

  - name: Committee
    identifier: committee
    weight: 50
  - name: Organizing Committee
    parent: committee
    url: oc
    weight: 51
  - name: Program Committee
    parent: committee
    url: pc
    weight: 52
  - name: Steering Committee
    parent: committee
    url: sc
    weight: 53

  - name: Sponsors
    url: sponsors
    weight: 70

  - name: Venue
    url: venue
    weight: 80

  - name: Others
    identifier: others
    weight: 90
  - name: Contact
    parent: others
    url: contact
    weight: 91
  - name: Past
    parent: others
    url: past
    weight: 92
