# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: news
    weight: 10

  - name: Calls
    identifier: calls
    weight: 20
  - name: Call for Papers
    parent: calls
    url: cfp
    weight: 21
  - name: Call for Posters
    parent: calls
    url: cfposters
    weight: 22
  - name: Call for Sponsors
    parent: calls
    url: cfs
    weight: 23
  - name: Call for Volunteers
    parent: calls
    url: cfv
    weight: 24
  - name: Call for Participation
    parent: calls
    url: APSys2024Brochure.pdf
    weight: 25

  - name: Program
    url: program
    weight: 30

  - name: Posters
    url: posters
    weight: 40

  - name: Sponsors
    url: sponsors
    weight: 50

  - name: Committee
    identifier: committee
    weight: 60
  - name: Organizing Committee
    parent: committee
    url: oc
    weight: 61
  - name: Program Committee
    parent: committee
    url: pc
    weight: 62
  - name: Steering Committee
    parent: committee
    url: sc
    weight: 63

  - name: Attend
    identifier: attend
    weight: 70
  - name: Registration
    parent: attend
    url: registration
    weight: 71
  - name: Visa
    parent: attend
    url: visa
    weight: 72
  - name: Hotel
    parent: attend
    url: hotel
    weight: 73

  - name: Venue
    url: venue
    weight: 80

  - name: Others
    identifier: others
    weight: 90
  - name: Contact
    parent: others
    url: contact
    weight: 91
  - name: Past
    parent: others
    url: past
    weight: 92
