# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: news
    weight: 10
  - name: Calls
    identifier: calls
    weight: 20
  - name: Call for Papers
    parent: calls
    url: cfp
    weight: 21
  - name: Call for Posters
    parent: calls
    url: cfposters
    weight: 22
  - name: Call for Sponsors
    parent: calls
    url: cfs
    weight: 23
  - name: Program
    identifier: program
    weight: 30
  - name: Program
    parent: program
    url: program
    weight: 31
  - name: Posters
    parent: program
    url: posters
    weight: 32
  - name: Accepted Papers
    parent: program
    url: papers
    weight: 33
  - name: Registration
    url: registration
    weight: 40
  - name: Visa
    url: visa
    weight: 50
  - name: Venue
    url: venue
    weight: 80
  - name: Others
    identifier: others
    weight: 90
  - name: Contact
    parent: others
    url: contact
    weight: 91
  - name: Past
    parent: others
    url: past
    weight: 92
  - name: Organization
    parent: others
    url: organization
    weight: 93
